// Drop the <sandbox_violations> footer from bash results before it reaches
// the model context.
//
// Every process spawned on macOS reads kern.iossupportversion once at startup
// (libsystem init), and the sandbox-exec profile generated by
// @anthropic-ai/sandbox-runtime denies sysctl-read, so each external command
// (ls, grep, cat, head, ...) used to append a multi-line noise block to every
// result. Live testing showed the block never carries unique signal beyond
// that noise: write/read denials arrive fully formed via the command's own
// stderr, and network denials come with a dedicated remediation hint on a
// separate channel — so the whole block goes, not just the noise lines.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

/**
 * One <sandbox_violations> block plus the single preceding/trailing newlines
 * that separate it from the command output. The whole match is deleted.
 */
const VIOLATIONS_BLOCK = /((?:\r?\n)?)[ \t]*<sandbox_violations>\r?\n([\s\S]*?)\r?\n?[ \t]*<\/sandbox_violations>((?:\r?\n)?)/g;


function stripNoise(text: string): string {
	return text.replace(VIOLATIONS_BLOCK, "");
}

export default function (pi: ExtensionAPI) {
	pi.on("tool_result", async (event) => {
		if (event.toolName !== "bash") return;
		if (typeof event.content === "string") {
			const cleaned = stripNoise(event.content);
			if (cleaned !== event.content) return { content: cleaned };
			return;
		}
		if (Array.isArray(event.content)) {
			let changed = false;
			const content = event.content.map((block: unknown) => {
				if (
					typeof block === "object" &&
					block !== null &&
					"text" in block &&
					typeof (block as { text: unknown }).text === "string"
				) {
					const text = (block as { text: string }).text;
					const cleaned = stripNoise(text);
					if (cleaned !== text) {
						changed = true;
						return { ...(block as Record<string, unknown>), text: cleaned };
					}
				}
				return block;
			});
			if (changed) return { content: content as typeof event.content };
		}
	});
}
